import React, { useEffect } from 'react'
import { useRouter } from 'next/router'
import { selectIsAuthenticated } from '@/store/selectors/authSelectors'
import { useSelector } from 'react-redux'
import { getSession } from '@/lib/cognito'

// Higher Order Component (HOC) for handling authentication logic
const withAuth = (WrappedComponent: React.FC) => {
  // Component generated by the HOC
  const WithAuthComponent: React.FC = props => {
    // Check if the user is authenticated using Redux selector
    const isAuthenticated = useSelector(selectIsAuthenticated)
    const router = useRouter()

    useEffect(() => {
      // If the user is not authenticated, redirect to the home page
      if (!isAuthenticated) {
        router.push('/')
      }

      // Refresh session when page reloads
      getSession().then().catch()
    }, [isAuthenticated, router])

    // Render the original component only if the user is authenticated
    return isAuthenticated ? <WrappedComponent {...props} /> : null
  }

  // Return the component generated by the HOC
  return WithAuthComponent
}

export default withAuth
